config/routes.rb
CatsProject::Application.routes.draw do

  root to: "cats#index"
  resources :cats
  resources :cat_rental_requests do
    member do
      post 'approve', 'deny'
    end
  end

  resources :users
  resource :session
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :birth_date, :color, :name, :sex, :user_id, presence: true
  validates :age, numericality: {only_integer: true}
  validates :sex, inclusion: { in: %w(M F)}
  validates :color, inclusion: { in: %(brown black white red blue yellow) }

  has_many(
    :cat_rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  belongs_to(
  :owner,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :no_overlapping_approvals
  before_validation :init_status

  belongs_to(
  :cat,
  class_name: "Cat",
  foreign_key: :cat_id,
  primary_key: :id

  )

  def no_overlapping_approvals
    if status == "APPROVED" && overlapping_approved_requests.count > 0
      errors.add(:base, "request overlaps with an approved request")
    end
  end

  def overlapping_requests
    existing_requests = CatRentalRequest.find_all_by_cat_id(cat_id)
    overlaps = []
    existing_requests.each do |existing_request|
      next if existing_request.id == id
      if (existing_request.start_date..existing_request.end_date).include?(self.start_date) ||
        (existing_request.start_date..existing_request.end_date).include?(self.end_date)
        overlaps << existing_request
      end
    end

    overlaps
  end

  def overlapping_pending_requests
    overlaps_with_approved = []

    overlapping_requests.each do |overlapping_request|
      if overlapping_request.status == "PENDING"
        overlaps_with_approved << overlapping_request
      end
    end

    overlaps_with_approved
  end

  def overlapping_approved_requests
    overlaps_with_approved = []

    overlapping_requests.each do |overlapping_request|
      if overlapping_request.status == "APPROVED"
        overlaps_with_approved << overlapping_request
      end
    end

    overlaps_with_approved
  end

  def approve!
    ActiveRecord::Base.transaction do
      self.update_attributes(status: "APPROVED")
      self.save!
      overlapping_pending_requests.each do |overlapping_request|
        overlapping_request.deny!
      end
    end
  end

  def deny!
    self.update_attributes(status: "DENIED")
    self.save!
  end



  protected

  def init_status
    @status ||= "PENDING"
  end
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :password_digest, :session_token, :user_name, :password

  validates :password_digest, :session_token, :user_name, presence: true
  validates :session_token, uniqueness: true

  before_validation :ensure_session_token

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    user.is_password?(password) ? user : nil
  end

  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_filter :require_correct_user!, only: [:approve, :deny]

  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all
  end

  def create
    CatRentalRequest.create(params[:cat_rental_request])
    @cats = Cat.all
    redirect_to @cats
  end

  def approve
    @current_cat_rental = CatRentalRequest.find(params[:id])
    @current_cat_rental.approve!
    current_cat = Cat.find(@current_cat_rental.cat_id)
    redirect_to current_cat
  end

  def deny
    @current_cat_rental = CatRentalRequest.find(params[:cat[:id]])
    @current_cat_rental.deny!
    current_cat = Cat.find(@current_cat_rental.cat_id)
    redirect_to current_cat
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_filter :require_correct_user!, only: [:edit, :new]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
    @cat_rental_requests = CatRentalRequest.find_all_by_cat_id(params[:id])
    @cat_rental_requests.sort! { |a,b| a.start_date <=> b.start_date } unless @cat_rental_requests.nil?
  end

  def new
    @cat = Cat.new
  end

  def create
    params[:cat][:user_id] = current_user.id
    @cat = Cat.new(params[:cat])
    if @cat.save
      redirect_to cat_url(@cat.id)
    else
      flash[:notice] ||= []
      flash[:notice] << "Cat couldn't be created!"
      redirect_to new_cat_url
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if @user.nil?
      flash[:notice] ||= []
      flash[:notice] << "Credentials were incorrect!"
      redirect_to new_session_url
    else
      login_user!
      redirect_to cats_url
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user!
      redirect_to cats_url
    else
      flash[:notice] ||= []
      flash[:notice] << @user.errors.full_messages
      redirect_to new_user_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def login_user!
    @user.session_token = User.generate_session_token
    @user.save!
    session[:session_token] = @user.session_token
  end

  def require_correct_user!
    if self.class == CatRentalRequestsController
      if current_user != CatRentalRequest.find(params[:id]).cat.owner
        flash[:notice] ||= []
        flash[:notice] << "You need to be the owner."
        redirect_to new_session_url
      end
    elsif self.class == CatsController
      if current_user != Cat.find(params[:id]).owner
        flash[:notice] ||= []
        flash[:notice] << "You need to be the owner."
        redirect_to new_session_url
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="/cat_rental_requests" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <select name="cat_rental_request[cat_id]" id="cat_rental_request_cat_id">
    <option value="Select One">Select One</option>
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>
  <label for="cat_rental_request_start_date">Rental Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" id="cat_rental_request_start_date">
  <br>
  <label for="cat_rental_request_end_date">Rental End Date</label>
  <input type="date" name="cat_rental_request[end_date]" id="cat_rental_request_end_date">
  <br>
  <input type="submit" value="Request cat rental">
</form>

app/views/cats/_form.html.erb
<form action="/cats" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if @cat.persisted? %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>
  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">
  <br>
  <label for="cat_age">Age</label>
  <input type="text" name="cat[age]" id="cat_age" value="<%= @cat.age %>">
  <br>
  <% checked = @cat.sex == "M" ? "checked" : "" %>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= checked.html_safe %>>
  <label for="cat_sex_male">Male</label>
  <br>
  <% checked = @cat.sex == "F" ? "checked" : "" %>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= checked.html_safe %>>
  <label for="cat_sex_female">Female</label>
  <br>
  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option value="Select One">Select One</option>
    <% selected = @cat.color == "brown" ? "selected" : "" %>
    <option value="brown" <%= selected.html_safe %>>Brown</option>
    <% selected = @cat.color == "black" ? "selected" : "" %>
    <option value="black" <%= selected.html_safe %>>Black</option>
    <% selected = @cat.color == "blue" ? "selected" : "" %>
    <option value="blue" <%= selected.html_safe %>>Blue</option>
    <% selected = @cat.color == "yellow" ? "selected" : "" %>
    <option value="yellow" <%= selected.html_safe %>>Yellow</option>
    <% selected = @cat.color == "red" ? "selected" : "" %>
    <option value="red" <%= selected.html_safe %>>Red</option>
    <% selected = @cat.color == "white" ? "selected" : "" %>
    <option value="white" <%= selected.html_safe %>>White</option>
  </select>
  <br>
  <label for="cat_birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" id="cat_birth_date" value=<%= @cat.birth_date %>>
  <br>
  <input type="submit" value="Update cat">
</form>

app/views/cats/edit.html.erb
<%= render 'form' %>

app/views/cats/index.html.erb
<ol>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_url(cat.id) %></li>
  <% end %>
</ol>

app/views/cats/new.html.erb
<%= render 'form' %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<table>

  <tr>
    <td>Age</td>
    <td>Birthdate</td>
    <td>Color</td>
    <td>Sex</td>
  </tr>
  <tr>
    <td><%= @cat.age %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
  </tr>

</table>
<br>
<br>
<table>
  <tr>
    <td>Cat Rental Request ID</td>
    <td>Start Date</td>
    <td>End Date</td>
    <td>Status</td>
    <td>Action</td>
  </tr>
  <% @cat_rental_requests.each do |rental_request| %>
  <tr>
    <td><%= rental_request.id %></td>
    <td><%= rental_request.start_date %></td>
    <td><%= rental_request.end_date %></td>
    <td><%= rental_request.status %></td>
    <td>
      <% if rental_request.status == "PENDING" %>
        <% if rental_request.cat.owner == current_user %>
          <%= button_to "Approve", approve_cat_rental_request_url(rental_request) %>
          <%= button_to "Deny", deny_cat_rental_request_url(rental_request) %>
        <%end%>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/layouts/_errors.html.erb
<% if flash[:notice] %>
  <% flash[:notice].each do |notice| %>
    <%= notice %><br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsProject</title>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "layouts/errors" %>
  <% if current_user.nil? %>
    <%= link_to "Click here to log in", new_session_url %>
  <% else %>
    <%= "Welcome #{current_user.user_name}" %> | <%= button_to "Log Out", session_url, method: :delete %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_user_name">User Name</label>
  <input type="text" name="user[user_name]" id="user_user_name" >
  <br>
  <label for="user_password">Password</label>
  <input type="text" name="user[password]" id="user_password" >
  <br>

  <br>
  <input type="submit" value="Sign Up">
</form>